- name: variables form files
  host: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hello, I am Learning {{COURSE}},Duration is: {{DURATION}}, : {{TRAINER}}"