- name: varibale from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Please enter the Course
  - name: TRAINER
    Prompt: Please enter the Trainer name
  - name: DURATION
    Prompt: Please enter the Duration
  tasks: 
  - name: Print course information
    ansible.builtin.debug:
     msg: "Hi, I am learning {{COURSE}}, Duration {{DURATION}},Trainer {{TRAINER}}" 

