- name: varibale from prompt
  hosts: web
  vars_prompt:
  
  vars_prompt:
  - name: COURSE
    prompt: Please enter the COURSE
    private: false
 
  - name: TRAINER
    prompt: Please enter the Trainer
    private: false   

  
  - name: DURATION
    prompt: Please enter the Duration
    private: false

  

  tasks: 
  - name: Print course information
    ansible.builtin.debug:
     msg: "Hi, I am learning {{COURSE}}, Duration {{DURATION}},Trainer {{TRAINER}}" 

