- name: create user
  hosts: web
  become: yes

  tasks: 
  - name: check user exit or not 
    ansible.builtin.command: id expense
    register: USER # user is a variable that get the output of the above command
    ignore_errors: true

  - name: print the user info
    ansible.builtin.debug:
      msg: "user info: {{ USER }}"

  - name: create user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0
