
- name: loops demo
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course| default(' Lohan ')}}"

  - name: conver to uppder case
    vars: 
      greatings: "Hello Raja Ram"
    ansible.builtin.debug:
      msg: "{{ greatings | upper }}"

  - name: conver to lower case
    vars: 
      greatings: "Hello Raja Ram"
    ansible.builtin.debug:
      msg: "{{ greatings | lower }}"


  - name: getting unique vales
    vars: 
      numbers: [1,4,6,2,1,2,3,2,3,4,1]
    ansible.builtin.debug:
      msg: " {{numbers | unique}} "

  - name: get min and max value
    vars: 
      numbers: [1,3,2,4,5,6,8,99]
    ansible.builtin.debug:
      msg: "min : {{ numbner | min }}, max: {{ number | max}}"

