- name: create ec2 and r53 instance
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-066b77e6dc99cb918 ## replace with your subnet id 
    sg_id: "sg-02aa4ba2517ec1ceb"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: lohanu.online
    
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance: 
     name: "{{ item }}"
     vpc_subnet_id: "{{ subnet_id }}"
     instance_type: "t3.micro"
     security_group: "{{ sg_id }}"
     image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
     msg: "{{ ec2_instances }}"


  - name: create r53 record
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" # mysql.lohanu.online
      type: A
      tt1: 1
      value: "{{ item.instances[0].private.ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"


